import AutomaticContinuity.Statement
import Mathlib.Tactic.Positivity
import Mathlib.Tactic.Push

/-!
# The bounded sequence extracted from an unbounded character

This file formalises the first, elementary step of the manuscript's reduction
proposition. It does not use multiplicativity, completeness, or separation.
-/

namespace AutomaticContinuity

universe u v

section Seminorms

variable {A : Type u} [AddCommGroup A] [Module ℂ A] [TopologicalSpace A]
variable {ι : Type v} {p : ι → Seminorm ℂ A}

/-- Multiplying the members of a bounded sequence by scalars of norm at most one
preserves boundedness in a topology generated by seminorms. -/
theorem isVonNBounded_range_smul_of_norm_le_one
    (hp : WithSeminorms p) {y : ℕ → A}
    (hy : Bornology.IsVonNBounded ℂ (Set.range y)) {c : ℕ → ℂ}
    (hc : ∀ n, ‖c n‖ ≤ 1) :
    Bornology.IsVonNBounded ℂ (Set.range (fun n => c n • y n)) := by
  apply hp.isVonNBounded_iff_seminorm_bounded.mpr
  intro i
  obtain ⟨r, hr, h⟩ := hp.isVonNBounded_iff_seminorm_bounded.mp hy i
  refine ⟨r, hr, ?_⟩
  rintro _ ⟨n, rfl⟩
  calc
    p i (c n • y n) = ‖c n‖ * p i (y n) := map_smul_eq_mul _ _ _
    _ ≤ 1 * p i (y n) := mul_le_mul_of_nonneg_right (hc n) (apply_nonneg _ _)
    _ = p i (y n) := one_mul _
    _ < r := h _ ⟨n, rfl⟩

end Seminorms

section Sequence

variable {A : Type u} [NonUnitalCommRing A] [Module ℂ A] [TopologicalSpace A]

/-- Negating boundedness on bounded sets produces a single bounded set on which
the image norms exceed every prescribed nonnegative real number. -/
theorem exists_unbounded_image_of_not_boundedOnBoundedSets
    {χ : A → ℂ} (hχ : ¬ BoundedOnBoundedSets A χ) :
    ∃ B : Set A, Bornology.IsVonNBounded ℂ B ∧
      ∀ C : ℝ, 0 ≤ C → ∃ a ∈ B, C < ‖χ a‖ := by
  classical
  unfold BoundedOnBoundedSets at hχ
  push Not at hχ
  exact hχ

/-- If a complex linear map is unbounded on some bounded set, a bounded sequence
can be rescaled to have the positive real images `4 * (n + 1)`.

This is the first paragraph of the reduction proposition, using natural-number
indices starting at zero. No multiplicativity is used in this construction. -/
theorem exists_bounded_sequence_of_not_boundedOnBoundedSets
    (hA : IsLocallyMultiplicativelyConvex A) (χ : A →ₗ[ℂ] ℂ)
    (hχ : ¬ BoundedOnBoundedSets A χ) :
    ∃ x : ℕ → A, Bornology.IsVonNBounded ℂ (Set.range x) ∧
      ∀ n : ℕ, χ (x n) = (4 : ℂ) * ((n : ℂ) + 1) := by
  classical
  obtain ⟨B, hB, hχ⟩ := exists_unbounded_image_of_not_boundedOnBoundedSets hχ
  have hex (n : ℕ) : ∃ a ∈ B, (4 * (n + 1) : ℕ) < ‖χ a‖ :=
    hχ _ (by positivity)
  choose y hyB hy using hex
  have hyBounded : Bornology.IsVonNBounded ℂ (Set.range y) :=
    hB.subset (by rintro _ ⟨n, rfl⟩; exact hyB n)
  let c : ℕ → ℂ := fun n => (4 * (n + 1) : ℕ) / χ (y n)
  have hyPos (n : ℕ) : 0 < ‖χ (y n)‖ := lt_of_le_of_lt (by positivity) (hy n)
  have hyNe (n : ℕ) : χ (y n) ≠ 0 := norm_pos_iff.mp (hyPos n)
  have hc (n : ℕ) : ‖c n‖ ≤ 1 := by
    dsimp [c]
    rw [norm_div, norm_natCast]
    exact (div_le_one (hyPos n)).mpr (hy n).le
  obtain ⟨P, _, hP⟩ := hA
  refine ⟨fun n => c n • y n,
    isVonNBounded_range_smul_of_norm_le_one hP hyBounded hc, ?_⟩
  intro n
  rw [map_smul, smul_eq_mul]
  dsimp [c]
  rw [div_mul_cancel₀ _ (hyNe n)]
  simp

/-- The normalised bounded sequence for an algebraic character. -/
theorem exists_bounded_sequence_of_unbounded_character
    (hA : IsLocallyMultiplicativelyConvex A) (χ : Character A)
    (hχ : ¬ BoundedOnBoundedSets A (fun a => χ.val a)) :
    ∃ x : ℕ → A, Bornology.IsVonNBounded ℂ (Set.range x) ∧
      ∀ n : ℕ, χ.val (x n) = (4 : ℂ) * ((n : ℂ) + 1) := by
  exact exists_bounded_sequence_of_not_boundedOnBoundedSets hA
    (χ.val : A →ₗ[ℂ] ℂ) hχ

end Sequence

end AutomaticContinuity
