import AutomaticContinuity.Statement
import AutomaticContinuity.Coefficients

set_option autoImplicit false

/-!
# The topology of the coefficient algebra

The defining family is precisely the positive integral coefficient seminorms.
The uniformity is the infimum of their additive uniformities, so no normability
or completeness is imposed by definition. Completeness is established separately
in `CoefficientCompleteness.lean`.
-/

noncomputable section

namespace AutomaticContinuity
namespace CoefficientSeries

open Filter
open scoped Topology

/-- Radius `n+1` avoids silently replacing the radius-one norm by radius zero. -/
def definingSeminorm (n : ℕ) : Seminorm ℂ CoefficientSeries := qSeminorm (n + 1)

@[simp] theorem definingSeminorm_apply (n : ℕ) (f : CoefficientSeries) :
    definingSeminorm n f = q (n + 1) f := rfl

/-- The standard additive uniformity generated by all the coefficient norms. -/
instance coefficientUniformSpace : UniformSpace CoefficientSeries :=
  ⨅ n : ℕ, (definingSeminorm n).toSeminormedAddCommGroup.toUniformSpace

instance coefficientIsUniformAddGroup : IsUniformAddGroup CoefficientSeries :=
  isUniformAddGroup_iInf fun n =>
    (definingSeminorm n).toSeminormedAddCommGroup.to_isUniformAddGroup

/-- This uniformity induces exactly the locally convex topology in the paper. -/
theorem withSeminorms : WithSeminorms definingSeminorm :=
  (SeminormFamily.withSeminorms_iff_uniformSpace_eq_iInf definingSeminorm).mpr rfl

instance coefficientContinuousSMul : ContinuousSMul ℂ CoefficientSeries :=
  withSeminorms.continuousSMul

instance coefficientT1Space : T1Space CoefficientSeries := by
  apply withSeminorms.T1_of_separating
  intro f hf
  refine ⟨0, ?_⟩
  simpa only [definingSeminorm_apply, zero_add] using
    (q_eq_zero_iff Nat.one_pos f).not.mpr hf

instance coefficientT2Space : T2Space CoefficientSeries := inferInstance

/-- Reindexing by the image set loses no defining seminorms. -/
theorem withSeminorms_range :
    WithSeminorms (fun p : Set.range definingSeminorm => p.val) := by
  classical
  apply withSeminorms.congr
  · intro p
    obtain ⟨n, hn⟩ := p.property
    refine ⟨{n}, 1, ?_⟩
    simp only [Seminorm.comp_id, Finset.sup_singleton, one_smul]
    exact le_of_eq hn.symm
  · intro n
    refine ⟨{⟨definingSeminorm n, Set.mem_range_self n⟩}, 1, ?_⟩
    simp

/-- The coefficient algebra has the same locally multiplicatively convex
structure used in the target statement. This does not yet assert completeness. -/
theorem isLocallyMultiplicativelyConvex :
    IsLocallyMultiplicativelyConvex CoefficientSeries := by
  refine ⟨Set.range definingSeminorm, ?_, withSeminorms_range⟩
  rintro p ⟨n, rfl⟩ f g
  exact q_mul_le (n + 1) f g

theorem continuous_definingSeminorm (n : ℕ) : Continuous (definingSeminorm n) :=
  withSeminorms.continuous_seminorm n

theorem bounded_iff_q (B : Set CoefficientSeries) :
    Bornology.IsVonNBounded ℂ B ↔
      ∀ n : ℕ, ∃ C > (0 : ℝ), ∀ f ∈ B, q (n + 1) f < C :=
  withSeminorms.isVonNBounded_iff_seminorm_bounded

/-- The coefficient algebra topology is first countable, as expected from its
countable defining family. This is not an assumption on general target algebras. -/
instance coefficientFirstCountableTopology : FirstCountableTopology CoefficientSeries :=
  withSeminorms.firstCountableTopology

/-- Finite coefficient truncations converge in the full locally convex topology. -/
theorem tendsto_truncate (f : CoefficientSeries) :
    Tendsto (fun s : Finset MultiIndex => truncate s f) atTop (𝓝 f) := by
  apply (withSeminorms.tendsto_nhds _ f).mpr
  intro n ε hε
  exact (tendsto_q_truncate_sub (n + 1) f).eventually (gt_mem_nhds hε)

/-- Finite polynomials are dense in the concrete coefficient algebra. -/
theorem polynomialHom_denseRange : DenseRange polynomialHom := by
  intro f
  apply mem_closure_of_tendsto (tendsto_truncate f)
  exact Eventually.of_forall fun s => ⟨truncationPolynomial s f, rfl⟩

/-- Each individual coefficient is a complex linear functional. -/
def coefficientLinearMap (α : MultiIndex) : CoefficientSeries →ₗ[ℂ] ℂ where
  toFun := fun f => coeff f α
  map_add' f g := by simp [coeff]
  map_smul' c f := by simp [coeff]

/-- Coefficients depend continuously on the series in the defining topology. -/
theorem continuous_coeff (α : MultiIndex) : Continuous (fun f : CoefficientSeries => coeff f α) := by
  apply withSeminorms.continuous_normedSpace_rng ℂ (coefficientLinearMap α)
  refine ⟨{0}, 1, ?_⟩
  simp only [Finset.sup_singleton, one_smul]
  intro f
  exact norm_coeff_le_q_one f α

end CoefficientSeries
end AutomaticContinuity
