import AutomaticContinuity.PolynomialConvexity
import Mathlib.Topology.ContinuousMap.Compact
import Mathlib.Topology.Algebra.Algebra
import Mathlib.Analysis.Normed.Algebra.Spectrum

/-!
# The Banach algebra of uniform limits of polynomial restrictions

For compact `K`, `P K` is the actual closed polynomial subalgebra of `C(K,ℂ)`
with its sup norm. Every algebraic complex character determines a point in the
polynomial hull. If `K` is polynomially convex, density identifies the character
with evaluation on every function in `P K`. The empty-set case is excluded by
the existence of the character itself, not by an extra geometric hypothesis.
-/

noncomputable section

namespace AutomaticContinuity.PolynomialFunctionAlgebra

open Set
open Filter
open scoped Topology

universe u

variable {σ : Type u}

/-- Restrict an actual polynomial to the given subset of coordinate space. -/
def restriction (K : Set (σ → ℂ)) : MvPolynomial σ ℂ →ₐ[ℂ] C(K, ℂ) :=
  MvPolynomial.aeval (fun j => ⟨fun x : K => x.val j,
    (continuous_apply j).comp continuous_subtype_val⟩)

@[simp] theorem restriction_apply (K : Set (σ → ℂ)) (p : MvPolynomial σ ℂ) (x : K) :
    restriction K p x = MvPolynomial.eval x.val p := by
  have heq : (ContinuousMap.evalAlgHom ℂ ℂ x).comp (restriction K) =
      MvPolynomial.aeval x.val := by
    ext j
    simp [restriction]
  exact AlgHom.congr_fun heq p

/-- The closed subalgebra of continuous functions generated by restrictions
of complex coordinate polynomials. -/
def algebra (K : Set (σ → ℂ)) [CompactSpace K] : Subalgebra ℂ C(K, ℂ) :=
  (restriction K).range.topologicalClosure

/-- Its underlying function algebra, retaining the inherited sup norm. -/
abbrev P (K : Set (σ → ℂ)) [CompactSpace K] := ↥(algebra K)

def polynomial (K : Set (σ → ℂ)) [CompactSpace K] : MvPolynomial σ ℂ →ₐ[ℂ] P K :=
  (restriction K).codRestrict (algebra K) fun p =>
    (restriction K).range.le_topologicalClosure (AlgHom.mem_range_self _ p)

@[simp] theorem polynomial_apply (K : Set (σ → ℂ)) [CompactSpace K]
    (p : MvPolynomial σ ℂ) (x : K) :
    (polynomial K p).val x = MvPolynomial.eval x.val p := restriction_apply K p x

theorem denseRange_polynomial (K : Set (σ → ℂ)) [CompactSpace K] : DenseRange (polynomial K) := by
  rw [DenseRange, Subtype.dense_iff]
  intro f hf
  change f ∈ closure (Set.range (restriction K)) at hf
  apply closure_mono ?_ hf
  rintro g ⟨p, rfl⟩
  exact ⟨polynomial K p, ⟨p, rfl⟩, rfl⟩

variable (K : Set (σ → ℂ)) [CompactSpace K]

instance : CompleteSpace (P K) :=
  (Subalgebra.isClosed_topologicalClosure (restriction K).range).isComplete.completeSpace_coe

instance [Nonempty K] : NormOneClass (P K) where
  norm_one := by
    change ‖(1 : C(K, ℂ))‖ = 1
    exact norm_one

/-- Approximation is in the actual sup norm of the function algebra. -/
theorem exists_polynomial_approx (f : P K) {ε : ℝ} (hε : 0 < ε) :
    ∃ p : MvPolynomial σ ℂ, ‖polynomial K p - f‖ < ε := by
  obtain ⟨p, hp⟩ := (denseRange_polynomial K).exists_dist_lt f hε
  exact ⟨p, by simpa only [dist_eq_norm, norm_sub_rev] using hp⟩

theorem norm_polynomial_le [Nonempty K] (p : MvPolynomial σ ℂ) {C : ℝ}
    (hC : ∀ x ∈ K, ‖MvPolynomial.eval x p‖ ≤ C) : ‖polynomial K p‖ ≤ C := by
  change ‖(polynomial K p).val‖ ≤ C
  exact (ContinuousMap.norm_le_of_nonempty _).mpr fun x => by
    rw [polynomial_apply]
    exact hC x x.property

theorem nonempty_of_character (η : P K →ₐ[ℂ] ℂ) : K.Nonempty := by
  by_contra hK
  have h01 : (0 : P K) = 1 := by
    apply Subtype.ext
    apply ContinuousMap.ext
    intro x
    exact False.elim (hK ⟨x.val, x.property⟩)
  have heq := congrArg η h01
  exact zero_ne_one (by simpa only [map_zero, map_one] using heq)

def characterPoint (η : P K →ₐ[ℂ] ℂ) : σ → ℂ :=
  fun j => η (polynomial K (MvPolynomial.X j))

theorem character_polynomial (η : P K →ₐ[ℂ] ℂ) (p : MvPolynomial σ ℂ) :
    η (polynomial K p) = MvPolynomial.eval (characterPoint K η) p := by
  have heq : η.comp (polynomial K) = MvPolynomial.aeval (characterPoint K η) := by
    ext j
    simp [characterPoint]
  exact AlgHom.congr_fun heq p

/-- The point determined by an algebraic character lies in the actual
polynomial hull, using automatic contractivity of Banach-algebra characters. -/
theorem character_point_mem_hull (η : P K →ₐ[ℂ] ℂ) :
    characterPoint K η ∈ polynomialHullOf (fun x : σ → ℂ => x) K := by
  obtain ⟨x, hx⟩ := nonempty_of_character K η
  let : Nonempty K := ⟨⟨x, hx⟩⟩
  intro p C hC
  rw [← character_polynomial K η p]
  exact (AlgHom.norm_apply_le_self η (polynomial K p)).trans (norm_polynomial_le K p hC)

/-- The hull point determines the entire character, since polynomial
restrictions are dense and every algebraic character is continuous. -/
theorem character_ext_of_point_eq (η θ : P K →ₐ[ℂ] ℂ)
    (heq : characterPoint K η = characterPoint K θ) : η = θ := by
  apply AlgHom.ext
  have hfun : (η : P K → ℂ) = θ := by
    apply (denseRange_polynomial K).equalizer (map_continuous η) (map_continuous θ)
    funext p
    rw [Function.comp_apply, Function.comp_apply, character_polynomial,
      character_polynomial, heq]
  exact congrFun hfun

/-- For a hull point coming from a character, evaluating any uniformly
convergent polynomial approximation recovers that character's value. This is
the evaluation interpretation even when the hull point lies outside `K`. -/
theorem tendsto_eval_characterPoint (η : P K →ₐ[ℂ] ℂ)
    {p : ℕ → MvPolynomial σ ℂ} {f : P K}
    (hp : Tendsto (fun n => polynomial K (p n)) atTop (𝓝 f)) :
    Tendsto (fun n => MvPolynomial.eval (characterPoint K η) (p n)) atTop (𝓝 (η f)) := by
  have h := (map_continuous η).continuousAt.tendsto.comp hp
  change Tendsto (fun n => η (polynomial K (p n))) atTop (𝓝 (η f)) at h
  simpa only [character_polynomial] using h

/-- If the compact set is polynomially convex, every algebraic character is
point evaluation on the whole closed polynomial function algebra. -/
theorem character_eq_evaluation
    (hK : IsPolynomiallyConvexOf (fun x : σ → ℂ => x) K) (η : P K →ₐ[ℂ] ℂ) :
    ∃ x : K, ∀ f : P K, η f = f.val x := by
  have hx : characterPoint K η ∈ K := by
    have hh := character_point_mem_hull K η
    rwa [hK] at hh
  let x : K := ⟨characterPoint K η, hx⟩
  refine ⟨x, ?_⟩
  have heq : (η : P K → ℂ) = fun f : P K => f.val x := by
    apply (denseRange_polynomial K).equalizer (map_continuous η)
      ((continuous_eval_const x).comp continuous_subtype_val)
    funext p
    exact (character_polynomial K η p).trans (polynomial_apply K p x).symm
  intro f
  exact congrFun heq f

end AutomaticContinuity.PolynomialFunctionAlgebra
