import Mathlib.Analysis.LocallyConvex.WithSeminorms
import Mathlib.Algebra.Algebra.NonUnitalHom
import Mathlib.Analysis.Complex.Basic

/-!
# Human-review statement of Theorem A

Source: `automatic_continuity_characters.tex`, Theorem A, label `thm:boundedness`.
Only the boundedness theorem is in scope; the automatic-continuity corollary is not.
`TheoremAStatement` below is a proposition definition, not a proof of Theorem A.

The algebra need not have a unit. Its additive uniform structure is required to be
compatible with addition, so `CompleteSpace` refers to the usual vector-space
uniformity. No countability, metrizability, or continuity of a character is assumed.
-/

namespace AutomaticContinuity

universe u

section Definitions

variable (A : Type u) [NonUnitalCommRing A] [Module ℂ A]

/-- An algebraic character: a nonzero complex-linear multiplicative map.
Mathlib's `NonUnitalAlgHom` imposes no continuity or boundedness. -/
abbrev Character := {χ : A →ₙₐ[ℂ] ℂ // χ ≠ 0}

/-- The additional inequality required of a defining seminorm. -/
def IsSubmultiplicative (p : Seminorm ℂ A) : Prop :=
  ∀ x y : A, p (x * y) ≤ p x * p y

variable [TopologicalSpace A]

/-- The topology is generated by some family of submultiplicative complex seminorms.
The index is an arbitrary set of seminorms; it is not assumed countable or nonempty.
`WithSeminorms` is Mathlib's equality with the topology generated by the family. -/
def IsLocallyMultiplicativelyConvex : Prop :=
  ∃ P : Set (Seminorm ℂ A),
    (∀ p ∈ P, IsSubmultiplicative A p) ∧
    WithSeminorms (fun p : P => p.val)

/-- Every bounded subset has a finite real bound on the moduli of its images.
The bound may depend on both the map and the subset. -/
def BoundedOnBoundedSets (χ : A → ℂ) : Prop :=
  ∀ B : Set A, Bornology.IsVonNBounded ℂ B →
    ∃ C : ℝ, 0 ≤ C ∧ ∀ a ∈ B, ‖χ a‖ ≤ C

end Definitions

/-- The full nonunital, not necessarily metrizable statement of Theorem A.
This names the target and does not assert it has been proved. -/
def TheoremAStatement : Prop :=
  ∀ (A : Type u) [NonUnitalCommRing A] [Module ℂ A]
    [IsScalarTower ℂ A A] [SMulCommClass ℂ A A]
    [UniformSpace A] [IsUniformAddGroup A] [T2Space A] [CompleteSpace A],
    IsLocallyMultiplicativelyConvex A →
    ∀ χ : Character A, BoundedOnBoundedSets A (fun a => χ.val a)

end AutomaticContinuity
