import AutomaticContinuity.Statement
import Mathlib.Algebra.Algebra.Unitization
import Mathlib.Topology.Algebra.IsUniformGroup.Constructions
import Mathlib.Topology.UniformSpace.Equiv
import Mathlib.Tactic.Ring

/-!
# Product uniformity and seminorms on a general unitization

Mathlib's normed unitization construction assumes a normed algebra. Here the
original algebra may have a topology generated by an arbitrary family of
seminorms. The instances are scoped: activate them with
`open scoped AutomaticContinuity.UnitizationTopology`.
-/

namespace AutomaticContinuity

noncomputable section

universe u

namespace UnitizationTopology

variable {A : Type u}

/-- The product uniformity on `ℂ × A`, transported to the algebraic unitization. -/
scoped instance productUniformSpace [UniformSpace A] : UniformSpace (Unitization ℂ A) :=
  UniformSpace.comap Unitization.toProd inferInstance

/-- The product equivalence for the chosen uniformity. -/
def uniformEquivProd [UniformSpace A] : Unitization ℂ A ≃ᵤ ℂ × A :=
  Equiv.toUniformEquivOfIsUniformInducing Unitization.equiv ⟨rfl⟩

scoped instance completeSpace [UniformSpace A] [CompleteSpace A] :
    CompleteSpace (Unitization ℂ A) :=
  uniformEquivProd.completeSpace_iff.mpr inferInstance

scoped instance t2Space [UniformSpace A] [T2Space A] : T2Space (Unitization ℂ A) :=
  uniformEquivProd.symm.toHomeomorph.t2Space

scoped instance isUniformAddGroup [AddCommGroup A] [UniformSpace A] [IsUniformAddGroup A] :
    IsUniformAddGroup (Unitization ℂ A) :=
  IsUniformInducing.isUniformAddGroup (Unitization.addEquiv ℂ A) ⟨rfl⟩

theorem continuous_fst [UniformSpace A] :
    Continuous (fun x : Unitization ℂ A => x.fst) :=
  _root_.continuous_fst.comp uniformEquivProd.continuous

theorem continuous_snd [UniformSpace A] :
    Continuous (fun x : Unitization ℂ A => x.snd) :=
  _root_.continuous_snd.comp uniformEquivProd.continuous

theorem continuous_inr [UniformSpace A] :
    Continuous (Unitization.inr : A → Unitization ℂ A) :=
  uniformEquivProd.symm.continuous.comp (continuous_const.prodMk continuous_id)

/-- The inclusion of the original space into its unitization is continuous and linear. -/
def inrCLM [AddCommGroup A] [Module ℂ A] [UniformSpace A] :
    A →L[ℂ] Unitization ℂ A :=
  ⟨Unitization.inrHom ℂ ℂ A, continuous_inr⟩

theorem isVonNBounded_image_inr [AddCommGroup A] [Module ℂ A] [UniformSpace A]
    {B : Set A} (hB : Bornology.IsVonNBounded ℂ B) :
    Bornology.IsVonNBounded ℂ ((Unitization.inr : A → Unitization ℂ A) '' B) :=
  hB.image inrCLM

section Seminorm

variable [NonUnitalCommRing A] [Module ℂ A]
variable [IsScalarTower ℂ A A] [SMulCommClass ℂ A A]

/-- The usual unitized seminorm `p#(z,a) = ‖z‖ + p(a)`. -/
def unitizedSeminorm (p : Seminorm ℂ A) : Seminorm ℂ (Unitization ℂ A) :=
  (normSeminorm ℂ ℂ).comp (Unitization.fstHom ℂ A).toLinearMap +
    p.comp (Unitization.sndHom ℂ ℂ A)

@[simp] theorem unitizedSeminorm_apply (p : Seminorm ℂ A) (x : Unitization ℂ A) :
    unitizedSeminorm p x = ‖x.fst‖ + p x.snd := rfl

@[simp] theorem unitizedSeminorm_inr (p : Seminorm ℂ A) (a : A) :
    unitizedSeminorm p (Unitization.inr a) = p a := by
  simp [unitizedSeminorm_apply]

@[simp] theorem unitizedSeminorm_one (p : Seminorm ℂ A) :
    unitizedSeminorm p 1 = 1 := by
  simp [unitizedSeminorm_apply]

/-- The extension preserves submultiplicativity. -/
theorem unitizedSeminorm_submultiplicative (p : Seminorm ℂ A)
    (hp : IsSubmultiplicative A p) :
    IsSubmultiplicative (Unitization ℂ A) (unitizedSeminorm p) := by
  intro x y
  simp only [unitizedSeminorm_apply, Unitization.fst_mul, Unitization.snd_mul, norm_mul]
  calc
    ‖x.fst‖ * ‖y.fst‖ + p (x.fst • y.snd + y.fst • x.snd + x.snd * y.snd)
      ≤ ‖x.fst‖ * ‖y.fst‖ +
        ((p (x.fst • y.snd) + p (y.fst • x.snd)) + p (x.snd * y.snd)) := by
          apply add_le_add le_rfl
          exact (map_add_le_add p _ _).trans
            (add_le_add (map_add_le_add p _ _) le_rfl)
    _ ≤ ‖x.fst‖ * ‖y.fst‖ +
        ((‖x.fst‖ * p y.snd + ‖y.fst‖ * p x.snd) + p x.snd * p y.snd) := by
          rw [map_smul_eq_mul, map_smul_eq_mul]
          exact add_le_add le_rfl (add_le_add le_rfl (hp _ _))
    _ = (‖x.fst‖ + p x.snd) * (‖y.fst‖ + p y.snd) := by ring

theorem continuous_unitizedSeminorm [UniformSpace A] (p : Seminorm ℂ A)
    (hp : Continuous p) : Continuous (unitizedSeminorm p) :=
  (continuous_fst.norm).add (hp.comp continuous_snd)

/-- Adjoin the scalar seminorm even when the original family is empty. -/
def unitizedFamily {ι : Type*} (p : ι → Seminorm ℂ A) :
    Option ι → Seminorm ℂ (Unitization ℂ A) :=
  fun i => unitizedSeminorm (i.elim 0 p)

open Filter Topology

theorem withSeminorms_unitizedFamily [UniformSpace A] [IsUniformAddGroup A]
    {ι : Type*} {p : ι → Seminorm ℂ A} (hp : WithSeminorms p) :
    WithSeminorms (unitizedFamily p) := by
  rw [SeminormFamily.withSeminorms_iff_nhds_eq_iInf]
  apply le_antisymm
  · refine le_iInf fun i => ?_
    apply tendsto_iff_comap.mp
    have hc : Continuous (unitizedFamily p i) := by
      apply continuous_unitizedSeminorm
      cases i with
      | none => exact continuous_const
      | some i => exact hp.continuous_seminorm i
    exact hc.tendsto' 0 0 (map_zero _)
  · let F : Filter (Unitization ℂ A) :=
      ⨅ i, (𝓝 (0 : ℝ)).comap (unitizedFamily p i)
    have hq (i : Option ι) : Tendsto (unitizedFamily p i) F (𝓝 (0 : ℝ)) :=
      tendsto_iff_comap.mpr (iInf_le _ i)
    have hfst : Tendsto (fun x : Unitization ℂ A => x.fst) F (𝓝 0) := by
      apply tendsto_zero_iff_norm_tendsto_zero.mpr
      have hq0 := hq none
      change Tendsto (fun x : Unitization ℂ A => ‖x.fst‖ + (0 : Seminorm ℂ A) x.snd)
        F (𝓝 0) at hq0
      simpa using hq0
    have hsnd : Tendsto (fun x : Unitization ℂ A => x.snd) F (𝓝 0) := by
      rw [(SeminormFamily.withSeminorms_iff_nhds_eq_iInf p).mp hp]
      apply tendsto_iInf.mpr
      intro i
      apply tendsto_comap_iff.mpr
      apply squeeze_zero (fun x : Unitization ℂ A => apply_nonneg (p i) x.snd)
        (fun x : Unitization ℂ A => le_add_of_nonneg_left (norm_nonneg x.fst))
      exact hq (some i)
    have hu := (uniformEquivProd (A := A)).symm.continuous.tendsto (0, 0)
      |>.comp (hfst.prodMk_nhds hsnd)
    change Tendsto id F (𝓝 0) at hu
    simpa only [tendsto_id'] using hu

/-- General, possibly nonnormable locally multiplicatively convex algebras retain
their defining property after unitization with the product uniformity. -/
theorem isLocallyMultiplicativelyConvex [UniformSpace A] [IsUniformAddGroup A]
    (hA : IsLocallyMultiplicativelyConvex A) :
    IsLocallyMultiplicativelyConvex (Unitization ℂ A) := by
  obtain ⟨P, hP, hp⟩ := hA
  let q := unitizedFamily (fun p : P => p.val)
  refine ⟨Set.range q, ?_, ?_⟩
  · rintro _ ⟨i, rfl⟩
    apply unitizedSeminorm_submultiplicative
    cases i with
    | none => intro x y; simp
    | some i => exact hP i.val i.property
  · have hq := withSeminorms_unitizedFamily hp
    rw [SeminormFamily.withSeminorms_iff_nhds_eq_iInf] at hq ⊢
    simpa only [iInf_subtype, iInf_range] using hq

end Seminorm

end UnitizationTopology

end

end AutomaticContinuity
